FROM docker.1ms.run/library/node:18-alpine

WORKDIR /app

RUN npm config set registry https://mirrors.ustc.edu.cn/npm/

COPY package*.json ./

RUN --mount=type=cache,target=/root/.npm npm install

COPY . .

EXPOSE 18112

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "18112"]
